### ISSUE TITLE
Create asp dot net core project and add EF model

### ISSUE THREAD

**Issue by yongzengyeo** [i66/product-qc-web#1]
Create asp dot net core project and add EF model
1) Use ASP Net Core 2.2
2) Need latest Microsoft.Net.Compilers

**Comment by yongzengyeo** [comment]
To create entity framework database first need run nuget 
Scaffold-DbContext "Data Source=192.168.15.201\SQLEXPRESS;Initial Catalog=Hexsave;Persist Security Info=True;User ID=hexbot;Password=xxx" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

**Comment by yongzengyeo** [comment]
Ref: https://docs.microsoft.com/zh-tw/ef/core/get-started/aspnetcore/existing-db

**Comment by yongzengyeo** [comment]
New asp .Net Core need set dbcontext in startup
https://stackoverflow.com/questions/46320189/asp-net-core-2-unable-to-resolve-service-for-type-microsoft-entityframeworkcore

**Comment by yongzengyeo** [comment]
Regex check for MachineNum
^(\d{1,3},\s*)*(\d{1,3})$

online check:https://regex101.com/

**Comment by wunyuhuang** [comment]
verify ok

**Comment by wunyuhuang** [comment]
verify ok
