### ISSUE TITLE
Deploy website and db to azure 

### ISSUE THREAD

**Issue by yongzengyeo** [i66/product-qc-web#12]
Deploy website and db to azure

**Comment by yongzengyeo** [comment]
use eunicehexsave@outlook.com account

**Comment by yongzengyeo** [comment]
DB Owner ID/Pass
hexbot
Hex54232885

**Comment by yongzengyeo** [comment]
![image](https://user-images.githubusercontent.com/30818445/51725948-dcee3b80-209f-11e9-8e29-c80fa5acd060.png)

**Comment by yongzengyeo** [comment]
![image](https://user-images.githubusercontent.com/30818445/51727736-4d00bf80-20a8-11e9-9a06-5681f5960558.png)

**Comment by yongzengyeo** [comment]
azure website：http://proquct-qc.azurewebsites.net

**Comment by wunyuhuang** [comment]
verify ok
