### ISSUE TITLE
Add reporting email function

### ISSUE THREAD

**Issue by wunyuhuang** [i66/product-qc-web#13]

**Comment by yongzengyeo** [comment]
verify OK

**Comment by wunyuhuang** [comment]
[Use **Memorystream** to attachment](https://stackoverflow.com/questions/5336239/attach-a-file-from-memorystream-to-a-mailmessage-in-c-sharp)

[Transfrom **linq sql** result to csv file](https://stackoverflow.com/questions/38316845/write-linq-query-results-to-csv-file-mvc)

**Comment by yongzengyeo** [comment]
verify OK again
