### ISSUE TITLE
Add 510, 511, 520 and 521 to QC page 

### ISSUE THREAD

**Issue by yongzengyeo** [i66/product-qc-web#15]
Add 510, 511, 520 and 521 to QC page

**Comment by yongzengyeo** [comment]
Regular expression also make sure first digit must be  either 1, 2, 3, 4

**Comment by yongzengyeo** [comment]
A510 - 1
A511 - 2
A520 - 3
A521 - 4

**Comment by wunyuhuang** [comment]
verify ok
