### ISSUE TITLE
Google single sign on

### ISSUE THREAD

**Issue by yongzengyeo** [i66/product-qc-web#17]
Google single sign on

**Comment by yongzengyeo** [comment]
https://docs.microsoft.com/zh-tw/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.2

**Comment by yongzengyeo** [comment]
JWT https://stackoverflow.com/questions/48727900/google-jwt-authentication-with-aspnet-core-2-0

**Comment by yongzengyeo** [comment]
ref:https://github.com/AnkitSharma-007/ASPCore.GoogleAuth/tree/master/GoogleAuth

**Comment by yongzengyeo** [comment]
https://blog.kevinyang.net/2018/05/31/aspnet-core-identity/

**Comment by yongzengyeo** [comment]
I hope I can authenticate without ASP identity~~~ Rework this task

**Comment by yongzengyeo** [comment]
Final Reference
https://www.jerriepelser.com/blog/forcing-users-sign-in-gsuite-domain-account/

**Comment by yongzengyeo** [comment]
google auth cannot accept local IP/ private ip
So using xip.io
the UAT test site became
http://192.168.15.201.xip.io:5000

**Comment by yongzengyeo** [comment]
setting page https://console.developers.google.com/apis/credentials?project=web-auth-1548838026797

**Comment by wunyuhuang** [comment]
verify ok
log in: google will also login. 
log out : close qc page(incognico mode) and log out google account.
