### ISSUE TITLE
Use paged list to show big host, small host, and repeater

### ISSUE THREAD

**Issue by yongzengyeo** [i66/product-qc-web#4]
Use paged list to show big host, small host, and repeater

**Comment by yongzengyeo** [comment]
use https://github.com/dncuug/X.PagedList

**Comment by yongzengyeo** [comment]
Revision: 62460e842caf0e654c574b012817c9f0893d7d97
Author: YongZengYeo <yongzengyeo@hexsave.com>
Date: 2019/1/15 下午 04:31:09
Message:
#2 add paged list

----
Modified: product-qc-web/Controllers/TDeliveriesController.cs
Modified: product-qc-web/Views/TDeliveries/Index.cshtml
Modified: product-qc-web/product-qc-web.csproj
Added: product-qc-web/wwwroot/css/PagedList.css

**Comment by yongzengyeo** [comment]
項次第一頁後要續加

**Comment by wunyuhuang** [comment]
verify ok
