### ISSUE TITLE
TDeliveries index page UI, words control, color and etc

### ISSUE THREAD

**Issue by yongzengyeo** [i66/product-qc-web#5]
TDeliveries index page UI, words control, color and etc

**Comment by yongzengyeo** [comment]
prototype
[Uploading 成品庫存與QC進度V1.0.pptx…]()

**Comment by yongzengyeo** [comment]
[成品庫存與QC進度V1.0.pptx](https://github.com/i66/product-qc-web/files/2766930/QC.V1.0.pptx)
protoype as template

**Comment by yongzengyeo** [comment]
fixed header 作法
https://codepen.io/tjvantoll/pen/JEKIu

**Comment by wunyuhuang** [comment]
verify ok
