### ISSUE TITLE
Deploy to Windows Slave of Jenkins

### ISSUE THREAD

**Issue by yongzengyeo** [i66/product-qc-web#9]
Deploy to Windows Slave of Jenkins

**Comment by yongzengyeo** [comment]
Deploy
http://192.168.15.201:5000/TDeliveries

**Comment by wunyuhuang** [comment]
Publish solution:
`dotnet publish --configuration Release --runtime win10-x64 --output QCWeb`
then can use 
`product-qc-web.exe --console` 
to run as localhost web process (127.0.0.1:5000).

verify ok
